# Generated by Django 3.1.5 on 2021-02-08 01:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='check_in_frequency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('daily', 'Daily'), ('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thurs', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='reminder_frequency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('daily', 'Daily'), ('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thurs', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='total_time',
            field=models.PositiveIntegerField(blank=True, help_text='Total time in hours, E.G. 10000 hours', null=True),
        ),
    ]
