# Generated by Django 3.1.5 on 2021-02-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210208_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='check_in_frequency',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='reminder_frequency',
        ),
    ]
