# Generated by Django 3.1.5 on 2021-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('check_in', 'Check In')], default='reminder', max_length=30),
            preserve_default=False,
        ),
    ]
